from app.schemas.signal import SignalData


def get_portfolio_risk() -> dict:
    return {
        "totalValue": 1250000,
        "totalGainLoss": 185000,
        "totalGainLossPercent": 17.4,
        "sectorExposure": [
            {"sector": "Technology", "weight": 45},
            {"sector": "Financials", "weight": 18},
            {"sector": "Healthcare", "weight": 15},
            {"sector": "Consumer Discretionary", "weight": 12},
            {"sector": "Energy", "weight": 10},
        ],
        "signalExposure": [
            {"signal": "strong-buy", "weight": 35},
            {"signal": "buy", "weight": 40},
            {"signal": "watch", "weight": 15},
            {"signal": "reduce", "weight": 8},
            {"signal": "sell", "weight": 2},
        ],
        "drawdownRisk": 15.5,
        "correlationMatrix": [
            [1.0, 0.85, 0.72, 0.45, 0.32],
            [0.85, 1.0, 0.68, 0.52, 0.28],
            [0.72, 0.68, 1.0, 0.38, 0.42],
            [0.45, 0.52, 0.38, 1.0, 0.55],
            [0.32, 0.28, 0.42, 0.55, 1.0],
        ],
        "positions": [
            {
                "ticker": "NVDA",
                "name": "NVIDIA Corp.",
                "shares": 150,
                "avgCost": 750.0,
                "currentPrice": 878.35,
                "marketValue": 131752.5,
                "gainLoss": 19252.5,
                "gainLossPercent": 17.1,
                "weight": 10.5,
                "sector": "Technology",
                "riskContribution": 2.8,
            },
            {
                "ticker": "AAPL",
                "name": "Apple Inc.",
                "shares": 500,
                "avgCost": 165.0,
                "currentPrice": 189.84,
                "marketValue": 94920.0,
                "gainLoss": 12420.0,
                "gainLossPercent": 15.1,
                "weight": 7.6,
                "sector": "Technology",
                "riskContribution": 1.8,
            },
            {
                "ticker": "MSFT",
                "name": "Microsoft Corp.",
                "shares": 300,
                "avgCost": 380.0,
                "currentPrice": 425.22,
                "marketValue": 127566.0,
                "gainLoss": 13566.0,
                "gainLossPercent": 11.9,
                "weight": 10.2,
                "sector": "Technology",
                "riskContribution": 2.2,
            },
            {
                "ticker": "JPM",
                "name": "JPMorgan Chase & Co.",
                "shares": 400,
                "avgCost": 175.0,
                "currentPrice": 198.45,
                "marketValue": 79380.0,
                "gainLoss": 9380.0,
                "gainLossPercent": 13.4,
                "weight": 6.4,
                "sector": "Financials",
                "riskContribution": 1.5,
            },
            {
                "ticker": "UNH",
                "name": "UnitedHealth Group",
                "shares": 200,
                "avgCost": 485.0,
                "currentPrice": 512.3,
                "marketValue": 102460.0,
                "gainLoss": 5460.0,
                "gainLossPercent": 5.6,
                "weight": 8.2,
                "sector": "Healthcare",
                "riskContribution": 1.2,
            },
        ],
    }
