"""initial_schema

Revision ID: 8282803e019a
Revises: 
Create Date: 2026-05-07 01:22:32.841557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8282803e019a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.create_table('backtest_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('tickers', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('annualized_return', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.Column('number_of_trades', sa.Integer(), nullable=True),
    sa.Column('avg_holding_period', sa.Float(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('drawdown_curve', sa.JSON(), nullable=True),
    sa.Column('monthly_returns', sa.JSON(), nullable=True),
    sa.Column('trade_distribution', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.String(length=36), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_backtest_id'), 'backtest_trades', ['backtest_id'], unique=False)
    op.create_table('breakout_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('breakout_level', sa.Float(), nullable=True),
    sa.Column('true_breakout_score', sa.Float(), nullable=True),
    sa.Column('false_breakout_risk', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('close_strength', sa.Float(), nullable=True),
    sa.Column('obv_confirmation', sa.Boolean(), nullable=True),
    sa.Column('rsi_divergence', sa.Boolean(), nullable=True),
    sa.Column('macd_divergence', sa.Boolean(), nullable=True),
    sa.Column('upper_chip_pressure', sa.Float(), nullable=True),
    sa.Column('sector_confirmation', sa.Float(), nullable=True),
    sa.Column('market_confirmation', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakout_signals_asset_id'), 'breakout_signals', ['asset_id'], unique=False)
    op.create_index(op.f('ix_breakout_signals_timestamp'), 'breakout_signals', ['timestamp'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('adjusted_close', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candles_asset_id'), 'candles', ['asset_id'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ma20', sa.Float(), nullable=True),
    sa.Column('ma60', sa.Float(), nullable=True),
    sa.Column('ma200', sa.Float(), nullable=True),
    sa.Column('ema20', sa.Float(), nullable=True),
    sa.Column('rsi14', sa.Float(), nullable=True),
    sa.Column('macd_line', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('adx', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('obv', sa.Float(), nullable=True),
    sa.Column('cmf', sa.Float(), nullable=True),
    sa.Column('mfi', sa.Float(), nullable=True),
    sa.Column('bollinger_upper', sa.Float(), nullable=True),
    sa.Column('bollinger_middle', sa.Float(), nullable=True),
    sa.Column('bollinger_lower', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('anchored_vwap', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_indicators_asset_id'), 'technical_indicators', ['asset_id'], unique=False)
    op.create_index(op.f('ix_technical_indicators_timestamp'), 'technical_indicators', ['timestamp'], unique=False)
    op.create_table('trade_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('signal', sa.String(length=20), nullable=True),
    sa.Column('buy_score', sa.Float(), nullable=True),
    sa.Column('sell_score', sa.Float(), nullable=True),
    sa.Column('entry_low', sa.Float(), nullable=True),
    sa.Column('entry_high', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('targets', sa.JSON(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('position_size_suggestion', sa.Float(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_signals_asset_id'), 'trade_signals', ['asset_id'], unique=False)
    op.create_index(op.f('ix_trade_signals_timestamp'), 'trade_signals', ['timestamp'], unique=False)
    op.create_table('volume_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('poc', sa.Float(), nullable=True),
    sa.Column('vah', sa.Float(), nullable=True),
    sa.Column('val', sa.Float(), nullable=True),
    sa.Column('chip_concentration_score', sa.Float(), nullable=True),
    sa.Column('upper_trapped_chip_pressure', sa.Float(), nullable=True),
    sa.Column('lower_support_density', sa.Float(), nullable=True),
    sa.Column('distribution', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volume_profiles_asset_id'), 'volume_profiles', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volume_profiles_asset_id'), table_name='volume_profiles')
    op.drop_table('volume_profiles')
    op.drop_index(op.f('ix_trade_signals_timestamp'), table_name='trade_signals')
    op.drop_index(op.f('ix_trade_signals_asset_id'), table_name='trade_signals')
    op.drop_table('trade_signals')
    op.drop_index(op.f('ix_technical_indicators_timestamp'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_asset_id'), table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_asset_id'), table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_breakout_signals_timestamp'), table_name='breakout_signals')
    op.drop_index(op.f('ix_breakout_signals_asset_id'), table_name='breakout_signals')
    op.drop_table('breakout_signals')
    op.drop_index(op.f('ix_backtest_trades_backtest_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
